### ISSUE TITLE
Where to put the commands showed in end of README.md

### ISSUE THREAD

**Issue by doronbehar** [varingst/awesome-constrain-mouse#1]
Hello @varingst,
I would very much like to use this plugin for [my awesome configuration](https://github.com/doronbehar/.config_awesome).

I added the first line in the `globalkeys` table as showed in the `README.md`, I understand that I should perhaps add a signal connection or something like it? My question is: where do I put the lines:
```lua
constr.constrain(c)  -- constrain mouse movement to client c
constr.constrain()   -- constrain to client under cursor
constr.release()     -- release the lock
```

**Comment by varingst** [comment]
You don't have to put them anywhere, and you can put them wherever you want. They are just provided in case someone wants to make something with them.
